version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make dev
    ports:
      - "8080:8080"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./app:/app
